name: nimreleaser

on:
  release:
    types:
      - published

env:
  APP_NAME: 'voicepeaky4gpt'
  NIM_VERSION: 'stable'
  MAINTAINER: 'solaoi'

jobs:
  build-artifact:
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: macOS-latest
            platform: darwin
            cpu: amd64
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y -d:release --threads:on
      - name: Create artifact
        run: |
          assets="${{ env.APP_NAME }}_${{ matrix.os.platform }}_${{ matrix.os.cpu }}"
          tar czf "$assets.tar.gz" "${{ env.APP_NAME }}"
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.os.name }}
          path: |
            *.tar.gz

  upload-release:
    runs-on: ubuntu-latest
    needs: build-artifact
    strategy:
      matrix:
        include:
          - os: macOS-latest
            asset_name_suffix: darwin_amd64.tar.gz
            asset_content_type: application/gzip
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact-${{ matrix.os }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.APP_NAME }}_${{ matrix.asset_name_suffix }}
          asset_name: ${{ env.APP_NAME }}_${{ matrix.asset_name_suffix }}
          asset_content_type: ${{ matrix.asset_content_type }}

  homebrew:
    runs-on: ubuntu-latest
    needs: upload-release
    steps:
      - name: Update Homebrew Formula
        uses: izumin5210/action-homebrew-tap@releases/v0
        with:
          tap: solaoi/homebrew-tap
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.TAP_GITHUB_TOKEN }}
          release-branch: main
          formula: voicepeaky4gpt.rb
          commit-message: Brew formula update for voicepeaky4gpt version ${{ env.RELEASE_VERSION }}
